# -*- coding: utf-8 -*-
"""Computer_vision_Assignment1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LYAOemJxsnPofVInzVpLZ9dutifeUs9p
"""

!git clone https://github.com/AJITKUMAR130012/Computer-vision.git

cd Computer-vision

!ls

cd Assignment1

!pip install easyocr

#import the required library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2 
import easyocr
import math

#read the image
img=cv2.imread("./Dataset/2/india-map.jpg")

#plot the image
plt.imshow(img)
plt.show()

#checking the shape of image
img.shape

#read the image using easyocr
reader = easyocr.Reader(['en'])
result = reader.readtext(img)

#print the result
print(result)

#checking length of the output by easy-ocr
n=len(result)
n

# result[i] contains the co-ordinate, word, and the probability value of correctness of word. 
len(result[0])

len(result[0][0])

# calculating the co-ordinate of the bihar and rajasthan
ans1=0
ans2=0
x1=0
y1=0
x2=0
y2=0
# calculating the mid point of the co-ordinate of the state
for i in range(n):
    if result[i][1]=="BIHAR":
        x1=(result[i][0][0][0] + result[i][0][1][0])/2
        y1=(result[i][0][0][1] + result[i][0][2][1])/2
        
    if result[i][1]=="RAJASTHAN":
        x2=(result[i][0][0][0] + result[i][0][1][0])/2
        y2=(result[i][0][0][1] + result[i][0][2][1])/2
print(x1,y1)
print(x2,y2)

p=[x1,y1]
q=[x2,y2]
print (math.dist(p, q))

