# -*- coding: utf-8 -*-
"""Computer_vision_Assignment1_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAISHrNTcHbRAEbmh0rnPrNPdarvtxEZ
"""

!git clone https://github.com/AJITKUMAR130012/Computer-vision.git

cd Computer-vision

cd Assignment1

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

img_rgb=cv2.imread("./Dataset/8/Ajit.jpg")
img=cv2.imread("./Dataset/8/Ajit.jpg",0)
template=cv2.imread("./Dataset/8/A2.jpg",0)

template.shape

template=cv2.resize(template,(256,256))

img_rgb.shape, img.shape, template.shape

plt.subplot(1,2,1)
plt.imshow(img_rgb)
plt.subplot(1,2,2)
plt.imshow(template)
plt.show()

w, h = template.shape[::-1]

res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)

threshold = 0.7

loc = np.where(res >= threshold)

img_rgb=cv2.imread("./Dataset/8/Ajit.jpg")

for pt in zip(*loc[::-1]):
    cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (0, 255, 255), 2)

plt.imshow(img_rgb)
plt.show()

