# -*- coding: utf-8 -*-
"""Computer_vision_Assignment1_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQT8qtiZX7FmTDWviJFbW0ALdpXvs-uf
"""

!git clone https://github.com/AJITKUMAR130012/Computer-vision.git

cd Computer-vision

cd Assignment1

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

img=cv2.imread("./Dataset/5/025a0eea25d9986b.jpg")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.imshow(img)
plt.show()

plt.hist(gray.flat, bins=10, edgecolor="yellow", color="green")

gray.shape, len((gray.flat))

hist_eq_img = cv2.equalizeHist(gray)

plt.imshow(hist_eq_img)
plt.show()

hist_eq_img.shape

plt.hist(hist_eq_img.flat, bins=10, edgecolor="yellow", color="green")

